version: 2
sources:
  - name: running_stage_data
    database: de-running-project
    schema: stage
    tables:
      - name: ultrarunning_data
        description: "This table aggregates event details along with athlete performance metrics."
        columns:
          - name: year_of_event
            description: "The year in which the event took place."
          - name: event_dates
            description: "The dates on which the event occurred."
          - name: event_name
            description: "The name of the event."
          - name: event_distance_length
            description: "The total length of the event: kilometers, miles or time."
          - name: event_num_finishers
            description: "The total number of athletes who finished the event."
          - name: athlete_performance
            description: "A time/distance measure of athlete performance."
          - name: athlete_club
            description: "The club or team of the athlete."
          - name: athlete_country
            description: "The country representation or origin of the athlete."
          - name: athlete_year_of_birth
            description: "The birth year of the athlete."
          - name: athlete_gender
            description: "The gender of the athlete."
          - name: athlete_age_category
            description: "A category or range indicating the age group of the athlete."
          - name: athlete_average_speed
            description: "The average speed of the athlete during the event in km/h."
          - name: athlete_id
            description: "A unique identifier for the athlete."
          - name: event_type
            description: "The type of event: Time or Duration."
          - name: distance_in_km
            description: "The distance of the event measured in kilometers."